apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: java-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: 899488875890.dkr.ecr.ap-northeast-1.amazonaws.com/aws-eks-demo:latest
        name: java-demo
        ports:
        - containerPort: 8080
