#!/bin/bash
export cluster_region_name="eu-west-3"
curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
chmod +x ./kubectl
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
kubectl version --short --client

curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
pwd

ls -ltr

eksctl get clusters --region=${cluster_region_name} | grep basic-cluster1

status=$?
if [ $status  -eq 0 ]
then
echo "cluster already created"
else
eksctl create cluster -f cluster_create.yml
fi

aws eks  update-kubeconfig --region ${cluster_region_name} --name basic-cluster1
kubectl get nodes
kubectl delete -f deploy.yml
kubectl apply -f deploy.yml
kubectl delete svc java-demo-service
kubectl expose deployment java-demo --type=LoadBalancer --name=java-demo-service
